// Code generated by ent, DO NOT EDIT.

package eventtype

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the eventtype type in the database.
	Label = "event_type"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEarthquakeID holds the string denoting the earthquake_id field in the database.
	FieldEarthquakeID = "earthquake_id"
	// FieldTypes holds the string denoting the types field in the database.
	FieldTypes = "types"
	// EdgeEarthquake holds the string denoting the earthquake edge name in mutations.
	EdgeEarthquake = "earthquake"
	// Table holds the table name of the eventtype in the database.
	Table = "Event_types"
	// EarthquakeTable is the table that holds the earthquake relation/edge.
	EarthquakeTable = "Event_types"
	// EarthquakeInverseTable is the table name for the Earthquake entity.
	// It exists in this package in order to avoid circular dependency with the "earthquake" package.
	EarthquakeInverseTable = "Earthquakes"
	// EarthquakeColumn is the table column denoting the earthquake relation/edge.
	EarthquakeColumn = "earthquake_id"
)

// Columns holds all SQL columns for eventtype fields.
var Columns = []string{
	FieldID,
	FieldEarthquakeID,
	FieldTypes,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the EventType queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByEarthquakeID orders the results by the earthquake_id field.
func ByEarthquakeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEarthquakeID, opts...).ToFunc()
}

// ByTypes orders the results by the types field.
func ByTypes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTypes, opts...).ToFunc()
}

// ByEarthquakeField orders the results by earthquake field.
func ByEarthquakeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEarthquakeStep(), sql.OrderByField(field, opts...))
	}
}
func newEarthquakeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EarthquakeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, EarthquakeTable, EarthquakeColumn),
	)
}
