// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
)

type APIRequestLog struct {
	ent.Schema
}

func (APIRequestLog) Fields() []ent.Field {
	return []ent.Field{field.Int("id"), 
	field.Time("request_datetime"), 
	field.JSON("request_parameters", map[string]interface{}{}), 
	field.JSON("request_body", map[string]interface{}{}), 
	field.JSON("request_headers", map[string]interface{}{}), 
	field.JSON("request_metadata", map[string]interface{}{}), 
	field.Time("created_at"), 
	field.Time("updated_at"),
	field.Time("deleted_at").Optional()}
}
func (APIRequestLog) Edges() []ent.Edge {
	return nil
}
func (APIRequestLog) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "API_request_logs"}}
}
