// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

type AssociatedEvent struct {
	ent.Schema
}

func (AssociatedEvent) Fields() []ent.Field {
	return []ent.Field{field.Int32("id"), field.Int32("earthquake_id").Optional(), field.Int32("associate_id").Optional()}
}
func (AssociatedEvent) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("main_event_earthquake", Earthquake.Type).Ref("associated_events").Unique().Field("associate_id"), 
		edge.From("associated_event_earthquake", Earthquake.Type).Ref("main_events").Unique().Field("earthquake_id")}
}
func (AssociatedEvent) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "Associated_events"}}
}
