// Code generated by entimport, DO NOT EDIT.

package schema

import "entgo.io/ent"

// Earthquake_db holds the schema definition for the Earthquake_db entity.
type Earthquake_db struct {
	ent.Schema
}

// Fields of the Earthquake_db.
func (Earthquake_db) Fields() []ent.Field {
	return nil
}

// Edges of the Earthquake_db.
func (Earthquake_db) Edges() []ent.Edge {
	return nil
}
