// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

type EventType struct {
	ent.Schema
}

func (EventType) Fields() []ent.Field {
	return []ent.Field{field.String("id").StorageKey("earthquake_id"), field.String("types").Optional()}
}
func (EventType) Edges() []ent.Edge {
	return []ent.Edge{edge.From("earthquake", Earthquake.Type).Ref("event_types").Unique().Field("earthquake_id")}
}
func (EventType) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "Event_types"}}
}
