// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

type FeatureType struct {
	ent.Schema
}

func (FeatureType) Fields() []ent.Field {
	return []ent.Field{field.String("id").StorageKey("earthquake_id"), field.String("feature_product_type")}
}
func (FeatureType) Edges() []ent.Edge {
	return []ent.Edge{edge.From("earthquake", Earthquake.Type).Ref("feature_types").Unique().Field("earthquake_id")}
}
func (FeatureType) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "Feature_types"}}
}
