// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

type FeltReport struct {
	ent.Schema
}

func (FeltReport) Fields() []ent.Field {
	return []ent.Field{field.Int32("id"), field.Int32("earthquake_id").Optional(), field.Int32("felt").Optional(), field.Float("cdi").Optional(), field.Float("mmi").Optional(), field.String("alert").Optional()}
}
func (FeltReport) Edges() []ent.Edge {
	return []ent.Edge{edge.From("earthquake", Earthquake.Type).Ref("felt_reports").Unique().Field("earthquake_id")}
}
func (FeltReport) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "Felt_reports"}}
}
