// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"entdemo/ent/apirequestlog"
	"entdemo/ent/predicate"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// APIRequestLogQuery is the builder for querying APIRequestLog entities.
type APIRequestLogQuery struct {
	config
	ctx        *QueryContext
	order      []apirequestlog.OrderOption
	inters     []Interceptor
	predicates []predicate.APIRequestLog
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the APIRequestLogQuery builder.
func (arlq *APIRequestLogQuery) Where(ps ...predicate.APIRequestLog) *APIRequestLogQuery {
	arlq.predicates = append(arlq.predicates, ps...)
	return arlq
}

// Limit the number of records to be returned by this query.
func (arlq *APIRequestLogQuery) Limit(limit int) *APIRequestLogQuery {
	arlq.ctx.Limit = &limit
	return arlq
}

// Offset to start from.
func (arlq *APIRequestLogQuery) Offset(offset int) *APIRequestLogQuery {
	arlq.ctx.Offset = &offset
	return arlq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (arlq *APIRequestLogQuery) Unique(unique bool) *APIRequestLogQuery {
	arlq.ctx.Unique = &unique
	return arlq
}

// Order specifies how the records should be ordered.
func (arlq *APIRequestLogQuery) Order(o ...apirequestlog.OrderOption) *APIRequestLogQuery {
	arlq.order = append(arlq.order, o...)
	return arlq
}

// First returns the first APIRequestLog entity from the query.
// Returns a *NotFoundError when no APIRequestLog was found.
func (arlq *APIRequestLogQuery) First(ctx context.Context) (*APIRequestLog, error) {
	nodes, err := arlq.Limit(1).All(setContextOp(ctx, arlq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{apirequestlog.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (arlq *APIRequestLogQuery) FirstX(ctx context.Context) *APIRequestLog {
	node, err := arlq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first APIRequestLog ID from the query.
// Returns a *NotFoundError when no APIRequestLog ID was found.
func (arlq *APIRequestLogQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = arlq.Limit(1).IDs(setContextOp(ctx, arlq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{apirequestlog.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (arlq *APIRequestLogQuery) FirstIDX(ctx context.Context) int {
	id, err := arlq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single APIRequestLog entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one APIRequestLog entity is found.
// Returns a *NotFoundError when no APIRequestLog entities are found.
func (arlq *APIRequestLogQuery) Only(ctx context.Context) (*APIRequestLog, error) {
	nodes, err := arlq.Limit(2).All(setContextOp(ctx, arlq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{apirequestlog.Label}
	default:
		return nil, &NotSingularError{apirequestlog.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (arlq *APIRequestLogQuery) OnlyX(ctx context.Context) *APIRequestLog {
	node, err := arlq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only APIRequestLog ID in the query.
// Returns a *NotSingularError when more than one APIRequestLog ID is found.
// Returns a *NotFoundError when no entities are found.
func (arlq *APIRequestLogQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = arlq.Limit(2).IDs(setContextOp(ctx, arlq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{apirequestlog.Label}
	default:
		err = &NotSingularError{apirequestlog.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (arlq *APIRequestLogQuery) OnlyIDX(ctx context.Context) int {
	id, err := arlq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of APIRequestLogs.
func (arlq *APIRequestLogQuery) All(ctx context.Context) ([]*APIRequestLog, error) {
	ctx = setContextOp(ctx, arlq.ctx, "All")
	if err := arlq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*APIRequestLog, *APIRequestLogQuery]()
	return withInterceptors[[]*APIRequestLog](ctx, arlq, qr, arlq.inters)
}

// AllX is like All, but panics if an error occurs.
func (arlq *APIRequestLogQuery) AllX(ctx context.Context) []*APIRequestLog {
	nodes, err := arlq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of APIRequestLog IDs.
func (arlq *APIRequestLogQuery) IDs(ctx context.Context) (ids []int, err error) {
	if arlq.ctx.Unique == nil && arlq.path != nil {
		arlq.Unique(true)
	}
	ctx = setContextOp(ctx, arlq.ctx, "IDs")
	if err = arlq.Select(apirequestlog.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (arlq *APIRequestLogQuery) IDsX(ctx context.Context) []int {
	ids, err := arlq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (arlq *APIRequestLogQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, arlq.ctx, "Count")
	if err := arlq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, arlq, querierCount[*APIRequestLogQuery](), arlq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (arlq *APIRequestLogQuery) CountX(ctx context.Context) int {
	count, err := arlq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (arlq *APIRequestLogQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, arlq.ctx, "Exist")
	switch _, err := arlq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (arlq *APIRequestLogQuery) ExistX(ctx context.Context) bool {
	exist, err := arlq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the APIRequestLogQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (arlq *APIRequestLogQuery) Clone() *APIRequestLogQuery {
	if arlq == nil {
		return nil
	}
	return &APIRequestLogQuery{
		config:     arlq.config,
		ctx:        arlq.ctx.Clone(),
		order:      append([]apirequestlog.OrderOption{}, arlq.order...),
		inters:     append([]Interceptor{}, arlq.inters...),
		predicates: append([]predicate.APIRequestLog{}, arlq.predicates...),
		// clone intermediate query.
		sql:  arlq.sql.Clone(),
		path: arlq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		RequestDatetime time.Time `json:"request_datetime,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.APIRequestLog.Query().
//		GroupBy(apirequestlog.FieldRequestDatetime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (arlq *APIRequestLogQuery) GroupBy(field string, fields ...string) *APIRequestLogGroupBy {
	arlq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &APIRequestLogGroupBy{build: arlq}
	grbuild.flds = &arlq.ctx.Fields
	grbuild.label = apirequestlog.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		RequestDatetime time.Time `json:"request_datetime,omitempty"`
//	}
//
//	client.APIRequestLog.Query().
//		Select(apirequestlog.FieldRequestDatetime).
//		Scan(ctx, &v)
func (arlq *APIRequestLogQuery) Select(fields ...string) *APIRequestLogSelect {
	arlq.ctx.Fields = append(arlq.ctx.Fields, fields...)
	sbuild := &APIRequestLogSelect{APIRequestLogQuery: arlq}
	sbuild.label = apirequestlog.Label
	sbuild.flds, sbuild.scan = &arlq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a APIRequestLogSelect configured with the given aggregations.
func (arlq *APIRequestLogQuery) Aggregate(fns ...AggregateFunc) *APIRequestLogSelect {
	return arlq.Select().Aggregate(fns...)
}

func (arlq *APIRequestLogQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range arlq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, arlq); err != nil {
				return err
			}
		}
	}
	for _, f := range arlq.ctx.Fields {
		if !apirequestlog.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if arlq.path != nil {
		prev, err := arlq.path(ctx)
		if err != nil {
			return err
		}
		arlq.sql = prev
	}
	return nil
}

func (arlq *APIRequestLogQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*APIRequestLog, error) {
	var (
		nodes = []*APIRequestLog{}
		_spec = arlq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*APIRequestLog).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &APIRequestLog{config: arlq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, arlq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (arlq *APIRequestLogQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := arlq.querySpec()
	_spec.Node.Columns = arlq.ctx.Fields
	if len(arlq.ctx.Fields) > 0 {
		_spec.Unique = arlq.ctx.Unique != nil && *arlq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, arlq.driver, _spec)
}

func (arlq *APIRequestLogQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(apirequestlog.Table, apirequestlog.Columns, sqlgraph.NewFieldSpec(apirequestlog.FieldID, field.TypeInt))
	_spec.From = arlq.sql
	if unique := arlq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if arlq.path != nil {
		_spec.Unique = true
	}
	if fields := arlq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, apirequestlog.FieldID)
		for i := range fields {
			if fields[i] != apirequestlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := arlq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := arlq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := arlq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := arlq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (arlq *APIRequestLogQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(arlq.driver.Dialect())
	t1 := builder.Table(apirequestlog.Table)
	columns := arlq.ctx.Fields
	if len(columns) == 0 {
		columns = apirequestlog.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if arlq.sql != nil {
		selector = arlq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if arlq.ctx.Unique != nil && *arlq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range arlq.predicates {
		p(selector)
	}
	for _, p := range arlq.order {
		p(selector)
	}
	if offset := arlq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := arlq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// APIRequestLogGroupBy is the group-by builder for APIRequestLog entities.
type APIRequestLogGroupBy struct {
	selector
	build *APIRequestLogQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (arlgb *APIRequestLogGroupBy) Aggregate(fns ...AggregateFunc) *APIRequestLogGroupBy {
	arlgb.fns = append(arlgb.fns, fns...)
	return arlgb
}

// Scan applies the selector query and scans the result into the given value.
func (arlgb *APIRequestLogGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, arlgb.build.ctx, "GroupBy")
	if err := arlgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*APIRequestLogQuery, *APIRequestLogGroupBy](ctx, arlgb.build, arlgb, arlgb.build.inters, v)
}

func (arlgb *APIRequestLogGroupBy) sqlScan(ctx context.Context, root *APIRequestLogQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(arlgb.fns))
	for _, fn := range arlgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*arlgb.flds)+len(arlgb.fns))
		for _, f := range *arlgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*arlgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := arlgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// APIRequestLogSelect is the builder for selecting fields of APIRequestLog entities.
type APIRequestLogSelect struct {
	*APIRequestLogQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (arls *APIRequestLogSelect) Aggregate(fns ...AggregateFunc) *APIRequestLogSelect {
	arls.fns = append(arls.fns, fns...)
	return arls
}

// Scan applies the selector query and scans the result into the given value.
func (arls *APIRequestLogSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, arls.ctx, "Select")
	if err := arls.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*APIRequestLogQuery, *APIRequestLogSelect](ctx, arls.APIRequestLogQuery, arls, arls.inters, v)
}

func (arls *APIRequestLogSelect) sqlScan(ctx context.Context, root *APIRequestLogQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(arls.fns))
	for _, fn := range arls.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*arls.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := arls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
