// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"entdemo/ent/earthquake_db"
	"entdemo/ent/predicate"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EarthquakeDbUpdate is the builder for updating Earthquake_db entities.
type EarthquakeDbUpdate struct {
	config
	hooks    []Hook
	mutation *EarthquakeDbMutation
}

// Where appends a list predicates to the EarthquakeDbUpdate builder.
func (edu *EarthquakeDbUpdate) Where(ps ...predicate.Earthquake_db) *EarthquakeDbUpdate {
	edu.mutation.Where(ps...)
	return edu
}

// Mutation returns the EarthquakeDbMutation object of the builder.
func (edu *EarthquakeDbUpdate) Mutation() *EarthquakeDbMutation {
	return edu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (edu *EarthquakeDbUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, edu.sqlSave, edu.mutation, edu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (edu *EarthquakeDbUpdate) SaveX(ctx context.Context) int {
	affected, err := edu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (edu *EarthquakeDbUpdate) Exec(ctx context.Context) error {
	_, err := edu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (edu *EarthquakeDbUpdate) ExecX(ctx context.Context) {
	if err := edu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (edu *EarthquakeDbUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(earthquake_db.Table, earthquake_db.Columns, sqlgraph.NewFieldSpec(earthquake_db.FieldID, field.TypeInt))
	if ps := edu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if n, err = sqlgraph.UpdateNodes(ctx, edu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{earthquake_db.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	edu.mutation.done = true
	return n, nil
}

// EarthquakeDbUpdateOne is the builder for updating a single Earthquake_db entity.
type EarthquakeDbUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EarthquakeDbMutation
}

// Mutation returns the EarthquakeDbMutation object of the builder.
func (eduo *EarthquakeDbUpdateOne) Mutation() *EarthquakeDbMutation {
	return eduo.mutation
}

// Where appends a list predicates to the EarthquakeDbUpdate builder.
func (eduo *EarthquakeDbUpdateOne) Where(ps ...predicate.Earthquake_db) *EarthquakeDbUpdateOne {
	eduo.mutation.Where(ps...)
	return eduo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (eduo *EarthquakeDbUpdateOne) Select(field string, fields ...string) *EarthquakeDbUpdateOne {
	eduo.fields = append([]string{field}, fields...)
	return eduo
}

// Save executes the query and returns the updated Earthquake_db entity.
func (eduo *EarthquakeDbUpdateOne) Save(ctx context.Context) (*Earthquake_db, error) {
	return withHooks(ctx, eduo.sqlSave, eduo.mutation, eduo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (eduo *EarthquakeDbUpdateOne) SaveX(ctx context.Context) *Earthquake_db {
	node, err := eduo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (eduo *EarthquakeDbUpdateOne) Exec(ctx context.Context) error {
	_, err := eduo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eduo *EarthquakeDbUpdateOne) ExecX(ctx context.Context) {
	if err := eduo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (eduo *EarthquakeDbUpdateOne) sqlSave(ctx context.Context) (_node *Earthquake_db, err error) {
	_spec := sqlgraph.NewUpdateSpec(earthquake_db.Table, earthquake_db.Columns, sqlgraph.NewFieldSpec(earthquake_db.FieldID, field.TypeInt))
	id, ok := eduo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Earthquake_db.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := eduo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, earthquake_db.FieldID)
		for _, f := range fields {
			if !earthquake_db.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != earthquake_db.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := eduo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &Earthquake_db{config: eduo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, eduo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{earthquake_db.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	eduo.mutation.done = true
	return _node, nil
}
