// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"entdemo/ent/earthquake_db"
	"entdemo/ent/predicate"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EarthquakeDbQuery is the builder for querying Earthquake_db entities.
type EarthquakeDbQuery struct {
	config
	ctx        *QueryContext
	order      []earthquake_db.OrderOption
	inters     []Interceptor
	predicates []predicate.Earthquake_db
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the EarthquakeDbQuery builder.
func (edq *EarthquakeDbQuery) Where(ps ...predicate.Earthquake_db) *EarthquakeDbQuery {
	edq.predicates = append(edq.predicates, ps...)
	return edq
}

// Limit the number of records to be returned by this query.
func (edq *EarthquakeDbQuery) Limit(limit int) *EarthquakeDbQuery {
	edq.ctx.Limit = &limit
	return edq
}

// Offset to start from.
func (edq *EarthquakeDbQuery) Offset(offset int) *EarthquakeDbQuery {
	edq.ctx.Offset = &offset
	return edq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (edq *EarthquakeDbQuery) Unique(unique bool) *EarthquakeDbQuery {
	edq.ctx.Unique = &unique
	return edq
}

// Order specifies how the records should be ordered.
func (edq *EarthquakeDbQuery) Order(o ...earthquake_db.OrderOption) *EarthquakeDbQuery {
	edq.order = append(edq.order, o...)
	return edq
}

// First returns the first Earthquake_db entity from the query.
// Returns a *NotFoundError when no Earthquake_db was found.
func (edq *EarthquakeDbQuery) First(ctx context.Context) (*Earthquake_db, error) {
	nodes, err := edq.Limit(1).All(setContextOp(ctx, edq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{earthquake_db.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (edq *EarthquakeDbQuery) FirstX(ctx context.Context) *Earthquake_db {
	node, err := edq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Earthquake_db ID from the query.
// Returns a *NotFoundError when no Earthquake_db ID was found.
func (edq *EarthquakeDbQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = edq.Limit(1).IDs(setContextOp(ctx, edq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{earthquake_db.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (edq *EarthquakeDbQuery) FirstIDX(ctx context.Context) int {
	id, err := edq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Earthquake_db entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Earthquake_db entity is found.
// Returns a *NotFoundError when no Earthquake_db entities are found.
func (edq *EarthquakeDbQuery) Only(ctx context.Context) (*Earthquake_db, error) {
	nodes, err := edq.Limit(2).All(setContextOp(ctx, edq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{earthquake_db.Label}
	default:
		return nil, &NotSingularError{earthquake_db.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (edq *EarthquakeDbQuery) OnlyX(ctx context.Context) *Earthquake_db {
	node, err := edq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Earthquake_db ID in the query.
// Returns a *NotSingularError when more than one Earthquake_db ID is found.
// Returns a *NotFoundError when no entities are found.
func (edq *EarthquakeDbQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = edq.Limit(2).IDs(setContextOp(ctx, edq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{earthquake_db.Label}
	default:
		err = &NotSingularError{earthquake_db.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (edq *EarthquakeDbQuery) OnlyIDX(ctx context.Context) int {
	id, err := edq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Earthquake_dbs.
func (edq *EarthquakeDbQuery) All(ctx context.Context) ([]*Earthquake_db, error) {
	ctx = setContextOp(ctx, edq.ctx, "All")
	if err := edq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Earthquake_db, *EarthquakeDbQuery]()
	return withInterceptors[[]*Earthquake_db](ctx, edq, qr, edq.inters)
}

// AllX is like All, but panics if an error occurs.
func (edq *EarthquakeDbQuery) AllX(ctx context.Context) []*Earthquake_db {
	nodes, err := edq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Earthquake_db IDs.
func (edq *EarthquakeDbQuery) IDs(ctx context.Context) (ids []int, err error) {
	if edq.ctx.Unique == nil && edq.path != nil {
		edq.Unique(true)
	}
	ctx = setContextOp(ctx, edq.ctx, "IDs")
	if err = edq.Select(earthquake_db.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (edq *EarthquakeDbQuery) IDsX(ctx context.Context) []int {
	ids, err := edq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (edq *EarthquakeDbQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, edq.ctx, "Count")
	if err := edq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, edq, querierCount[*EarthquakeDbQuery](), edq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (edq *EarthquakeDbQuery) CountX(ctx context.Context) int {
	count, err := edq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (edq *EarthquakeDbQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, edq.ctx, "Exist")
	switch _, err := edq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (edq *EarthquakeDbQuery) ExistX(ctx context.Context) bool {
	exist, err := edq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the EarthquakeDbQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (edq *EarthquakeDbQuery) Clone() *EarthquakeDbQuery {
	if edq == nil {
		return nil
	}
	return &EarthquakeDbQuery{
		config:     edq.config,
		ctx:        edq.ctx.Clone(),
		order:      append([]earthquake_db.OrderOption{}, edq.order...),
		inters:     append([]Interceptor{}, edq.inters...),
		predicates: append([]predicate.Earthquake_db{}, edq.predicates...),
		// clone intermediate query.
		sql:  edq.sql.Clone(),
		path: edq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (edq *EarthquakeDbQuery) GroupBy(field string, fields ...string) *EarthquakeDbGroupBy {
	edq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &EarthquakeDbGroupBy{build: edq}
	grbuild.flds = &edq.ctx.Fields
	grbuild.label = earthquake_db.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (edq *EarthquakeDbQuery) Select(fields ...string) *EarthquakeDbSelect {
	edq.ctx.Fields = append(edq.ctx.Fields, fields...)
	sbuild := &EarthquakeDbSelect{EarthquakeDbQuery: edq}
	sbuild.label = earthquake_db.Label
	sbuild.flds, sbuild.scan = &edq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a EarthquakeDbSelect configured with the given aggregations.
func (edq *EarthquakeDbQuery) Aggregate(fns ...AggregateFunc) *EarthquakeDbSelect {
	return edq.Select().Aggregate(fns...)
}

func (edq *EarthquakeDbQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range edq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, edq); err != nil {
				return err
			}
		}
	}
	for _, f := range edq.ctx.Fields {
		if !earthquake_db.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if edq.path != nil {
		prev, err := edq.path(ctx)
		if err != nil {
			return err
		}
		edq.sql = prev
	}
	return nil
}

func (edq *EarthquakeDbQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Earthquake_db, error) {
	var (
		nodes = []*Earthquake_db{}
		_spec = edq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Earthquake_db).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Earthquake_db{config: edq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, edq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (edq *EarthquakeDbQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := edq.querySpec()
	_spec.Node.Columns = edq.ctx.Fields
	if len(edq.ctx.Fields) > 0 {
		_spec.Unique = edq.ctx.Unique != nil && *edq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, edq.driver, _spec)
}

func (edq *EarthquakeDbQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(earthquake_db.Table, earthquake_db.Columns, sqlgraph.NewFieldSpec(earthquake_db.FieldID, field.TypeInt))
	_spec.From = edq.sql
	if unique := edq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if edq.path != nil {
		_spec.Unique = true
	}
	if fields := edq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, earthquake_db.FieldID)
		for i := range fields {
			if fields[i] != earthquake_db.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := edq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := edq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := edq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := edq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (edq *EarthquakeDbQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(edq.driver.Dialect())
	t1 := builder.Table(earthquake_db.Table)
	columns := edq.ctx.Fields
	if len(columns) == 0 {
		columns = earthquake_db.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if edq.sql != nil {
		selector = edq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if edq.ctx.Unique != nil && *edq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range edq.predicates {
		p(selector)
	}
	for _, p := range edq.order {
		p(selector)
	}
	if offset := edq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := edq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// EarthquakeDbGroupBy is the group-by builder for Earthquake_db entities.
type EarthquakeDbGroupBy struct {
	selector
	build *EarthquakeDbQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (edgb *EarthquakeDbGroupBy) Aggregate(fns ...AggregateFunc) *EarthquakeDbGroupBy {
	edgb.fns = append(edgb.fns, fns...)
	return edgb
}

// Scan applies the selector query and scans the result into the given value.
func (edgb *EarthquakeDbGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, edgb.build.ctx, "GroupBy")
	if err := edgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EarthquakeDbQuery, *EarthquakeDbGroupBy](ctx, edgb.build, edgb, edgb.build.inters, v)
}

func (edgb *EarthquakeDbGroupBy) sqlScan(ctx context.Context, root *EarthquakeDbQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(edgb.fns))
	for _, fn := range edgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*edgb.flds)+len(edgb.fns))
		for _, f := range *edgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*edgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := edgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// EarthquakeDbSelect is the builder for selecting fields of EarthquakeDb entities.
type EarthquakeDbSelect struct {
	*EarthquakeDbQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (eds *EarthquakeDbSelect) Aggregate(fns ...AggregateFunc) *EarthquakeDbSelect {
	eds.fns = append(eds.fns, fns...)
	return eds
}

// Scan applies the selector query and scans the result into the given value.
func (eds *EarthquakeDbSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, eds.ctx, "Select")
	if err := eds.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EarthquakeDbQuery, *EarthquakeDbSelect](ctx, eds.EarthquakeDbQuery, eds, eds.inters, v)
}

func (eds *EarthquakeDbSelect) sqlScan(ctx context.Context, root *EarthquakeDbQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(eds.fns))
	for _, fn := range eds.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*eds.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := eds.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
