// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"entdemo/ent/earthquake_db"
	"entdemo/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EarthquakeDbDelete is the builder for deleting a Earthquake_db entity.
type EarthquakeDbDelete struct {
	config
	hooks    []Hook
	mutation *EarthquakeDbMutation
}

// Where appends a list predicates to the EarthquakeDbDelete builder.
func (edd *EarthquakeDbDelete) Where(ps ...predicate.Earthquake_db) *EarthquakeDbDelete {
	edd.mutation.Where(ps...)
	return edd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (edd *EarthquakeDbDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, edd.sqlExec, edd.mutation, edd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (edd *EarthquakeDbDelete) ExecX(ctx context.Context) int {
	n, err := edd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (edd *EarthquakeDbDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(earthquake_db.Table, sqlgraph.NewFieldSpec(earthquake_db.FieldID, field.TypeInt))
	if ps := edd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, edd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	edd.mutation.done = true
	return affected, err
}

// EarthquakeDbDeleteOne is the builder for deleting a single Earthquake_db entity.
type EarthquakeDbDeleteOne struct {
	edd *EarthquakeDbDelete
}

// Where appends a list predicates to the EarthquakeDbDelete builder.
func (eddo *EarthquakeDbDeleteOne) Where(ps ...predicate.Earthquake_db) *EarthquakeDbDeleteOne {
	eddo.edd.mutation.Where(ps...)
	return eddo
}

// Exec executes the deletion query.
func (eddo *EarthquakeDbDeleteOne) Exec(ctx context.Context) error {
	n, err := eddo.edd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{earthquake_db.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (eddo *EarthquakeDbDeleteOne) ExecX(ctx context.Context) {
	if err := eddo.Exec(ctx); err != nil {
		panic(err)
	}
}
