// Code generated by ent, DO NOT EDIT.

package ent

import (
	"entdemo/ent/earthquake"
	"entdemo/ent/eventtype"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// EventType is the model entity for the EventType schema.
type EventType struct {
	config `json:"-"`
	// ID of the ent.
	ID int32 `json:"id,omitempty"`
	// EarthquakeID holds the value of the "earthquake_id" field.
	EarthquakeID int32 `json:"earthquake_id,omitempty"`
	// Types holds the value of the "types" field.
	Types string `json:"types,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EventTypeQuery when eager-loading is set.
	Edges        EventTypeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// EventTypeEdges holds the relations/edges for other nodes in the graph.
type EventTypeEdges struct {
	// Earthquake holds the value of the earthquake edge.
	Earthquake *Earthquake `json:"earthquake,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// EarthquakeOrErr returns the Earthquake value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EventTypeEdges) EarthquakeOrErr() (*Earthquake, error) {
	if e.Earthquake != nil {
		return e.Earthquake, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: earthquake.Label}
	}
	return nil, &NotLoadedError{edge: "earthquake"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EventType) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case eventtype.FieldID, eventtype.FieldEarthquakeID:
			values[i] = new(sql.NullInt64)
		case eventtype.FieldTypes:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EventType fields.
func (et *EventType) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case eventtype.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			et.ID = int32(value.Int64)
		case eventtype.FieldEarthquakeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field earthquake_id", values[i])
			} else if value.Valid {
				et.EarthquakeID = int32(value.Int64)
			}
		case eventtype.FieldTypes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field types", values[i])
			} else if value.Valid {
				et.Types = value.String
			}
		default:
			et.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the EventType.
// This includes values selected through modifiers, order, etc.
func (et *EventType) Value(name string) (ent.Value, error) {
	return et.selectValues.Get(name)
}

// QueryEarthquake queries the "earthquake" edge of the EventType entity.
func (et *EventType) QueryEarthquake() *EarthquakeQuery {
	return NewEventTypeClient(et.config).QueryEarthquake(et)
}

// Update returns a builder for updating this EventType.
// Note that you need to call EventType.Unwrap() before calling this method if this EventType
// was returned from a transaction, and the transaction was committed or rolled back.
func (et *EventType) Update() *EventTypeUpdateOne {
	return NewEventTypeClient(et.config).UpdateOne(et)
}

// Unwrap unwraps the EventType entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (et *EventType) Unwrap() *EventType {
	_tx, ok := et.config.driver.(*txDriver)
	if !ok {
		panic("ent: EventType is not a transactional entity")
	}
	et.config.driver = _tx.drv
	return et
}

// String implements the fmt.Stringer.
func (et *EventType) String() string {
	var builder strings.Builder
	builder.WriteString("EventType(")
	builder.WriteString(fmt.Sprintf("id=%v, ", et.ID))
	builder.WriteString("earthquake_id=")
	builder.WriteString(fmt.Sprintf("%v", et.EarthquakeID))
	builder.WriteString(", ")
	builder.WriteString("types=")
	builder.WriteString(et.Types)
	builder.WriteByte(')')
	return builder.String()
}

// EventTypes is a parsable slice of EventType.
type EventTypes []*EventType
