// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"entdemo/ent/earthquake"
	"entdemo/ent/featuretype"
	"entdemo/ent/predicate"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FeatureTypeUpdate is the builder for updating FeatureType entities.
type FeatureTypeUpdate struct {
	config
	hooks    []Hook
	mutation *FeatureTypeMutation
}

// Where appends a list predicates to the FeatureTypeUpdate builder.
func (ftu *FeatureTypeUpdate) Where(ps ...predicate.FeatureType) *FeatureTypeUpdate {
	ftu.mutation.Where(ps...)
	return ftu
}

// SetEarthquakeID sets the "earthquake_id" field.
func (ftu *FeatureTypeUpdate) SetEarthquakeID(i int32) *FeatureTypeUpdate {
	ftu.mutation.SetEarthquakeID(i)
	return ftu
}

// SetNillableEarthquakeID sets the "earthquake_id" field if the given value is not nil.
func (ftu *FeatureTypeUpdate) SetNillableEarthquakeID(i *int32) *FeatureTypeUpdate {
	if i != nil {
		ftu.SetEarthquakeID(*i)
	}
	return ftu
}

// ClearEarthquakeID clears the value of the "earthquake_id" field.
func (ftu *FeatureTypeUpdate) ClearEarthquakeID() *FeatureTypeUpdate {
	ftu.mutation.ClearEarthquakeID()
	return ftu
}

// SetFeatureProductType sets the "feature_product_type" field.
func (ftu *FeatureTypeUpdate) SetFeatureProductType(s string) *FeatureTypeUpdate {
	ftu.mutation.SetFeatureProductType(s)
	return ftu
}

// SetNillableFeatureProductType sets the "feature_product_type" field if the given value is not nil.
func (ftu *FeatureTypeUpdate) SetNillableFeatureProductType(s *string) *FeatureTypeUpdate {
	if s != nil {
		ftu.SetFeatureProductType(*s)
	}
	return ftu
}

// SetEarthquake sets the "earthquake" edge to the Earthquake entity.
func (ftu *FeatureTypeUpdate) SetEarthquake(e *Earthquake) *FeatureTypeUpdate {
	return ftu.SetEarthquakeID(e.ID)
}

// Mutation returns the FeatureTypeMutation object of the builder.
func (ftu *FeatureTypeUpdate) Mutation() *FeatureTypeMutation {
	return ftu.mutation
}

// ClearEarthquake clears the "earthquake" edge to the Earthquake entity.
func (ftu *FeatureTypeUpdate) ClearEarthquake() *FeatureTypeUpdate {
	ftu.mutation.ClearEarthquake()
	return ftu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ftu *FeatureTypeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ftu.sqlSave, ftu.mutation, ftu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ftu *FeatureTypeUpdate) SaveX(ctx context.Context) int {
	affected, err := ftu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ftu *FeatureTypeUpdate) Exec(ctx context.Context) error {
	_, err := ftu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ftu *FeatureTypeUpdate) ExecX(ctx context.Context) {
	if err := ftu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ftu *FeatureTypeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(featuretype.Table, featuretype.Columns, sqlgraph.NewFieldSpec(featuretype.FieldID, field.TypeInt32))
	if ps := ftu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ftu.mutation.FeatureProductType(); ok {
		_spec.SetField(featuretype.FieldFeatureProductType, field.TypeString, value)
	}
	if ftu.mutation.EarthquakeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   featuretype.EarthquakeTable,
			Columns: []string{featuretype.EarthquakeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(earthquake.FieldID, field.TypeInt32),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ftu.mutation.EarthquakeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   featuretype.EarthquakeTable,
			Columns: []string{featuretype.EarthquakeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(earthquake.FieldID, field.TypeInt32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ftu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{featuretype.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ftu.mutation.done = true
	return n, nil
}

// FeatureTypeUpdateOne is the builder for updating a single FeatureType entity.
type FeatureTypeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FeatureTypeMutation
}

// SetEarthquakeID sets the "earthquake_id" field.
func (ftuo *FeatureTypeUpdateOne) SetEarthquakeID(i int32) *FeatureTypeUpdateOne {
	ftuo.mutation.SetEarthquakeID(i)
	return ftuo
}

// SetNillableEarthquakeID sets the "earthquake_id" field if the given value is not nil.
func (ftuo *FeatureTypeUpdateOne) SetNillableEarthquakeID(i *int32) *FeatureTypeUpdateOne {
	if i != nil {
		ftuo.SetEarthquakeID(*i)
	}
	return ftuo
}

// ClearEarthquakeID clears the value of the "earthquake_id" field.
func (ftuo *FeatureTypeUpdateOne) ClearEarthquakeID() *FeatureTypeUpdateOne {
	ftuo.mutation.ClearEarthquakeID()
	return ftuo
}

// SetFeatureProductType sets the "feature_product_type" field.
func (ftuo *FeatureTypeUpdateOne) SetFeatureProductType(s string) *FeatureTypeUpdateOne {
	ftuo.mutation.SetFeatureProductType(s)
	return ftuo
}

// SetNillableFeatureProductType sets the "feature_product_type" field if the given value is not nil.
func (ftuo *FeatureTypeUpdateOne) SetNillableFeatureProductType(s *string) *FeatureTypeUpdateOne {
	if s != nil {
		ftuo.SetFeatureProductType(*s)
	}
	return ftuo
}

// SetEarthquake sets the "earthquake" edge to the Earthquake entity.
func (ftuo *FeatureTypeUpdateOne) SetEarthquake(e *Earthquake) *FeatureTypeUpdateOne {
	return ftuo.SetEarthquakeID(e.ID)
}

// Mutation returns the FeatureTypeMutation object of the builder.
func (ftuo *FeatureTypeUpdateOne) Mutation() *FeatureTypeMutation {
	return ftuo.mutation
}

// ClearEarthquake clears the "earthquake" edge to the Earthquake entity.
func (ftuo *FeatureTypeUpdateOne) ClearEarthquake() *FeatureTypeUpdateOne {
	ftuo.mutation.ClearEarthquake()
	return ftuo
}

// Where appends a list predicates to the FeatureTypeUpdate builder.
func (ftuo *FeatureTypeUpdateOne) Where(ps ...predicate.FeatureType) *FeatureTypeUpdateOne {
	ftuo.mutation.Where(ps...)
	return ftuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ftuo *FeatureTypeUpdateOne) Select(field string, fields ...string) *FeatureTypeUpdateOne {
	ftuo.fields = append([]string{field}, fields...)
	return ftuo
}

// Save executes the query and returns the updated FeatureType entity.
func (ftuo *FeatureTypeUpdateOne) Save(ctx context.Context) (*FeatureType, error) {
	return withHooks(ctx, ftuo.sqlSave, ftuo.mutation, ftuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ftuo *FeatureTypeUpdateOne) SaveX(ctx context.Context) *FeatureType {
	node, err := ftuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ftuo *FeatureTypeUpdateOne) Exec(ctx context.Context) error {
	_, err := ftuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ftuo *FeatureTypeUpdateOne) ExecX(ctx context.Context) {
	if err := ftuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ftuo *FeatureTypeUpdateOne) sqlSave(ctx context.Context) (_node *FeatureType, err error) {
	_spec := sqlgraph.NewUpdateSpec(featuretype.Table, featuretype.Columns, sqlgraph.NewFieldSpec(featuretype.FieldID, field.TypeInt32))
	id, ok := ftuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FeatureType.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ftuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, featuretype.FieldID)
		for _, f := range fields {
			if !featuretype.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != featuretype.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ftuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ftuo.mutation.FeatureProductType(); ok {
		_spec.SetField(featuretype.FieldFeatureProductType, field.TypeString, value)
	}
	if ftuo.mutation.EarthquakeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   featuretype.EarthquakeTable,
			Columns: []string{featuretype.EarthquakeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(earthquake.FieldID, field.TypeInt32),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ftuo.mutation.EarthquakeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   featuretype.EarthquakeTable,
			Columns: []string{featuretype.EarthquakeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(earthquake.FieldID, field.TypeInt32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &FeatureType{config: ftuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ftuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{featuretype.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ftuo.mutation.done = true
	return _node, nil
}
