// Code generated by ent, DO NOT EDIT.

package ent

import (
	"entdemo/ent/earthquake"
	"entdemo/ent/geometry"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Geometry is the model entity for the Geometry schema.
type Geometry struct {
	config `json:"-"`
	// ID of the ent.
	ID int32 `json:"id,omitempty"`
	// EarthquakeID holds the value of the "earthquake_id" field.
	EarthquakeID int32 `json:"earthquake_id,omitempty"`
	// Longitude holds the value of the "longitude" field.
	Longitude float64 `json:"longitude,omitempty"`
	// Latitude holds the value of the "latitude" field.
	Latitude float64 `json:"latitude,omitempty"`
	// Depth holds the value of the "depth" field.
	Depth float64 `json:"depth,omitempty"`
	// Place holds the value of the "place" field.
	Place string `json:"place,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GeometryQuery when eager-loading is set.
	Edges        GeometryEdges `json:"edges"`
	selectValues sql.SelectValues
}

// GeometryEdges holds the relations/edges for other nodes in the graph.
type GeometryEdges struct {
	// Earthquake holds the value of the earthquake edge.
	Earthquake *Earthquake `json:"earthquake,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// EarthquakeOrErr returns the Earthquake value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GeometryEdges) EarthquakeOrErr() (*Earthquake, error) {
	if e.Earthquake != nil {
		return e.Earthquake, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: earthquake.Label}
	}
	return nil, &NotLoadedError{edge: "earthquake"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Geometry) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case geometry.FieldLongitude, geometry.FieldLatitude, geometry.FieldDepth:
			values[i] = new(sql.NullFloat64)
		case geometry.FieldID, geometry.FieldEarthquakeID:
			values[i] = new(sql.NullInt64)
		case geometry.FieldPlace:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Geometry fields.
func (ge *Geometry) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case geometry.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ge.ID = int32(value.Int64)
		case geometry.FieldEarthquakeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field earthquake_id", values[i])
			} else if value.Valid {
				ge.EarthquakeID = int32(value.Int64)
			}
		case geometry.FieldLongitude:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field longitude", values[i])
			} else if value.Valid {
				ge.Longitude = value.Float64
			}
		case geometry.FieldLatitude:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field latitude", values[i])
			} else if value.Valid {
				ge.Latitude = value.Float64
			}
		case geometry.FieldDepth:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field depth", values[i])
			} else if value.Valid {
				ge.Depth = value.Float64
			}
		case geometry.FieldPlace:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field place", values[i])
			} else if value.Valid {
				ge.Place = value.String
			}
		default:
			ge.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Geometry.
// This includes values selected through modifiers, order, etc.
func (ge *Geometry) Value(name string) (ent.Value, error) {
	return ge.selectValues.Get(name)
}

// QueryEarthquake queries the "earthquake" edge of the Geometry entity.
func (ge *Geometry) QueryEarthquake() *EarthquakeQuery {
	return NewGeometryClient(ge.config).QueryEarthquake(ge)
}

// Update returns a builder for updating this Geometry.
// Note that you need to call Geometry.Unwrap() before calling this method if this Geometry
// was returned from a transaction, and the transaction was committed or rolled back.
func (ge *Geometry) Update() *GeometryUpdateOne {
	return NewGeometryClient(ge.config).UpdateOne(ge)
}

// Unwrap unwraps the Geometry entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ge *Geometry) Unwrap() *Geometry {
	_tx, ok := ge.config.driver.(*txDriver)
	if !ok {
		panic("ent: Geometry is not a transactional entity")
	}
	ge.config.driver = _tx.drv
	return ge
}

// String implements the fmt.Stringer.
func (ge *Geometry) String() string {
	var builder strings.Builder
	builder.WriteString("Geometry(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ge.ID))
	builder.WriteString("earthquake_id=")
	builder.WriteString(fmt.Sprintf("%v", ge.EarthquakeID))
	builder.WriteString(", ")
	builder.WriteString("longitude=")
	builder.WriteString(fmt.Sprintf("%v", ge.Longitude))
	builder.WriteString(", ")
	builder.WriteString("latitude=")
	builder.WriteString(fmt.Sprintf("%v", ge.Latitude))
	builder.WriteString(", ")
	builder.WriteString("depth=")
	builder.WriteString(fmt.Sprintf("%v", ge.Depth))
	builder.WriteString(", ")
	builder.WriteString("place=")
	builder.WriteString(ge.Place)
	builder.WriteByte(')')
	return builder.String()
}

// Geometries is a parsable slice of Geometry.
type Geometries []*Geometry
