// Code generated by ent, DO NOT EDIT.

package apirequestlog

import (
	"entdemo/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.APIRequestLog {
	return predicate.APIRequestLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.APIRequestLog {
	return predicate.APIRequestLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.APIRequestLog {
	return predicate.APIRequestLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.APIRequestLog {
	return predicate.APIRequestLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.APIRequestLog {
	return predicate.APIRequestLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.APIRequestLog {
	return predicate.APIRequestLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.APIRequestLog {
	return predicate.APIRequestLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.APIRequestLog {
	return predicate.APIRequestLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.APIRequestLog {
	return predicate.APIRequestLog(sql.FieldLTE(FieldID, id))
}

// RequestDatetime applies equality check predicate on the "request_datetime" field. It's identical to RequestDatetimeEQ.
func RequestDatetime(v time.Time) predicate.APIRequestLog {
	return predicate.APIRequestLog(sql.FieldEQ(FieldRequestDatetime, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.APIRequestLog {
	return predicate.APIRequestLog(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.APIRequestLog {
	return predicate.APIRequestLog(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.APIRequestLog {
	return predicate.APIRequestLog(sql.FieldEQ(FieldDeletedAt, v))
}

// RequestDatetimeEQ applies the EQ predicate on the "request_datetime" field.
func RequestDatetimeEQ(v time.Time) predicate.APIRequestLog {
	return predicate.APIRequestLog(sql.FieldEQ(FieldRequestDatetime, v))
}

// RequestDatetimeNEQ applies the NEQ predicate on the "request_datetime" field.
func RequestDatetimeNEQ(v time.Time) predicate.APIRequestLog {
	return predicate.APIRequestLog(sql.FieldNEQ(FieldRequestDatetime, v))
}

// RequestDatetimeIn applies the In predicate on the "request_datetime" field.
func RequestDatetimeIn(vs ...time.Time) predicate.APIRequestLog {
	return predicate.APIRequestLog(sql.FieldIn(FieldRequestDatetime, vs...))
}

// RequestDatetimeNotIn applies the NotIn predicate on the "request_datetime" field.
func RequestDatetimeNotIn(vs ...time.Time) predicate.APIRequestLog {
	return predicate.APIRequestLog(sql.FieldNotIn(FieldRequestDatetime, vs...))
}

// RequestDatetimeGT applies the GT predicate on the "request_datetime" field.
func RequestDatetimeGT(v time.Time) predicate.APIRequestLog {
	return predicate.APIRequestLog(sql.FieldGT(FieldRequestDatetime, v))
}

// RequestDatetimeGTE applies the GTE predicate on the "request_datetime" field.
func RequestDatetimeGTE(v time.Time) predicate.APIRequestLog {
	return predicate.APIRequestLog(sql.FieldGTE(FieldRequestDatetime, v))
}

// RequestDatetimeLT applies the LT predicate on the "request_datetime" field.
func RequestDatetimeLT(v time.Time) predicate.APIRequestLog {
	return predicate.APIRequestLog(sql.FieldLT(FieldRequestDatetime, v))
}

// RequestDatetimeLTE applies the LTE predicate on the "request_datetime" field.
func RequestDatetimeLTE(v time.Time) predicate.APIRequestLog {
	return predicate.APIRequestLog(sql.FieldLTE(FieldRequestDatetime, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.APIRequestLog {
	return predicate.APIRequestLog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.APIRequestLog {
	return predicate.APIRequestLog(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.APIRequestLog {
	return predicate.APIRequestLog(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.APIRequestLog {
	return predicate.APIRequestLog(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.APIRequestLog {
	return predicate.APIRequestLog(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.APIRequestLog {
	return predicate.APIRequestLog(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.APIRequestLog {
	return predicate.APIRequestLog(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.APIRequestLog {
	return predicate.APIRequestLog(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.APIRequestLog {
	return predicate.APIRequestLog(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.APIRequestLog {
	return predicate.APIRequestLog(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.APIRequestLog {
	return predicate.APIRequestLog(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.APIRequestLog {
	return predicate.APIRequestLog(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.APIRequestLog {
	return predicate.APIRequestLog(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.APIRequestLog {
	return predicate.APIRequestLog(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.APIRequestLog {
	return predicate.APIRequestLog(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.APIRequestLog {
	return predicate.APIRequestLog(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.APIRequestLog {
	return predicate.APIRequestLog(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.APIRequestLog {
	return predicate.APIRequestLog(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.APIRequestLog {
	return predicate.APIRequestLog(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.APIRequestLog {
	return predicate.APIRequestLog(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.APIRequestLog {
	return predicate.APIRequestLog(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.APIRequestLog {
	return predicate.APIRequestLog(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.APIRequestLog {
	return predicate.APIRequestLog(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.APIRequestLog {
	return predicate.APIRequestLog(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.APIRequestLog {
	return predicate.APIRequestLog(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.APIRequestLog {
	return predicate.APIRequestLog(sql.FieldNotNull(FieldDeletedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.APIRequestLog) predicate.APIRequestLog {
	return predicate.APIRequestLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.APIRequestLog) predicate.APIRequestLog {
	return predicate.APIRequestLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.APIRequestLog) predicate.APIRequestLog {
	return predicate.APIRequestLog(sql.NotPredicates(p))
}
