// Code generated by ent, DO NOT EDIT.

package feltreport

import (
	"entdemo/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int32) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int32) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int32) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int32) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int32) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int32) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int32) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int32) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int32) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldLTE(FieldID, id))
}

// EarthquakeID applies equality check predicate on the "earthquake_id" field. It's identical to EarthquakeIDEQ.
func EarthquakeID(v int32) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldEQ(FieldEarthquakeID, v))
}

// Felt applies equality check predicate on the "felt" field. It's identical to FeltEQ.
func Felt(v int32) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldEQ(FieldFelt, v))
}

// Cdi applies equality check predicate on the "cdi" field. It's identical to CdiEQ.
func Cdi(v float64) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldEQ(FieldCdi, v))
}

// Mmi applies equality check predicate on the "mmi" field. It's identical to MmiEQ.
func Mmi(v float64) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldEQ(FieldMmi, v))
}

// Alert applies equality check predicate on the "alert" field. It's identical to AlertEQ.
func Alert(v string) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldEQ(FieldAlert, v))
}

// EarthquakeIDEQ applies the EQ predicate on the "earthquake_id" field.
func EarthquakeIDEQ(v int32) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldEQ(FieldEarthquakeID, v))
}

// EarthquakeIDNEQ applies the NEQ predicate on the "earthquake_id" field.
func EarthquakeIDNEQ(v int32) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldNEQ(FieldEarthquakeID, v))
}

// EarthquakeIDIn applies the In predicate on the "earthquake_id" field.
func EarthquakeIDIn(vs ...int32) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldIn(FieldEarthquakeID, vs...))
}

// EarthquakeIDNotIn applies the NotIn predicate on the "earthquake_id" field.
func EarthquakeIDNotIn(vs ...int32) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldNotIn(FieldEarthquakeID, vs...))
}

// EarthquakeIDIsNil applies the IsNil predicate on the "earthquake_id" field.
func EarthquakeIDIsNil() predicate.FeltReport {
	return predicate.FeltReport(sql.FieldIsNull(FieldEarthquakeID))
}

// EarthquakeIDNotNil applies the NotNil predicate on the "earthquake_id" field.
func EarthquakeIDNotNil() predicate.FeltReport {
	return predicate.FeltReport(sql.FieldNotNull(FieldEarthquakeID))
}

// FeltEQ applies the EQ predicate on the "felt" field.
func FeltEQ(v int32) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldEQ(FieldFelt, v))
}

// FeltNEQ applies the NEQ predicate on the "felt" field.
func FeltNEQ(v int32) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldNEQ(FieldFelt, v))
}

// FeltIn applies the In predicate on the "felt" field.
func FeltIn(vs ...int32) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldIn(FieldFelt, vs...))
}

// FeltNotIn applies the NotIn predicate on the "felt" field.
func FeltNotIn(vs ...int32) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldNotIn(FieldFelt, vs...))
}

// FeltGT applies the GT predicate on the "felt" field.
func FeltGT(v int32) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldGT(FieldFelt, v))
}

// FeltGTE applies the GTE predicate on the "felt" field.
func FeltGTE(v int32) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldGTE(FieldFelt, v))
}

// FeltLT applies the LT predicate on the "felt" field.
func FeltLT(v int32) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldLT(FieldFelt, v))
}

// FeltLTE applies the LTE predicate on the "felt" field.
func FeltLTE(v int32) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldLTE(FieldFelt, v))
}

// FeltIsNil applies the IsNil predicate on the "felt" field.
func FeltIsNil() predicate.FeltReport {
	return predicate.FeltReport(sql.FieldIsNull(FieldFelt))
}

// FeltNotNil applies the NotNil predicate on the "felt" field.
func FeltNotNil() predicate.FeltReport {
	return predicate.FeltReport(sql.FieldNotNull(FieldFelt))
}

// CdiEQ applies the EQ predicate on the "cdi" field.
func CdiEQ(v float64) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldEQ(FieldCdi, v))
}

// CdiNEQ applies the NEQ predicate on the "cdi" field.
func CdiNEQ(v float64) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldNEQ(FieldCdi, v))
}

// CdiIn applies the In predicate on the "cdi" field.
func CdiIn(vs ...float64) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldIn(FieldCdi, vs...))
}

// CdiNotIn applies the NotIn predicate on the "cdi" field.
func CdiNotIn(vs ...float64) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldNotIn(FieldCdi, vs...))
}

// CdiGT applies the GT predicate on the "cdi" field.
func CdiGT(v float64) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldGT(FieldCdi, v))
}

// CdiGTE applies the GTE predicate on the "cdi" field.
func CdiGTE(v float64) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldGTE(FieldCdi, v))
}

// CdiLT applies the LT predicate on the "cdi" field.
func CdiLT(v float64) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldLT(FieldCdi, v))
}

// CdiLTE applies the LTE predicate on the "cdi" field.
func CdiLTE(v float64) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldLTE(FieldCdi, v))
}

// CdiIsNil applies the IsNil predicate on the "cdi" field.
func CdiIsNil() predicate.FeltReport {
	return predicate.FeltReport(sql.FieldIsNull(FieldCdi))
}

// CdiNotNil applies the NotNil predicate on the "cdi" field.
func CdiNotNil() predicate.FeltReport {
	return predicate.FeltReport(sql.FieldNotNull(FieldCdi))
}

// MmiEQ applies the EQ predicate on the "mmi" field.
func MmiEQ(v float64) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldEQ(FieldMmi, v))
}

// MmiNEQ applies the NEQ predicate on the "mmi" field.
func MmiNEQ(v float64) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldNEQ(FieldMmi, v))
}

// MmiIn applies the In predicate on the "mmi" field.
func MmiIn(vs ...float64) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldIn(FieldMmi, vs...))
}

// MmiNotIn applies the NotIn predicate on the "mmi" field.
func MmiNotIn(vs ...float64) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldNotIn(FieldMmi, vs...))
}

// MmiGT applies the GT predicate on the "mmi" field.
func MmiGT(v float64) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldGT(FieldMmi, v))
}

// MmiGTE applies the GTE predicate on the "mmi" field.
func MmiGTE(v float64) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldGTE(FieldMmi, v))
}

// MmiLT applies the LT predicate on the "mmi" field.
func MmiLT(v float64) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldLT(FieldMmi, v))
}

// MmiLTE applies the LTE predicate on the "mmi" field.
func MmiLTE(v float64) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldLTE(FieldMmi, v))
}

// MmiIsNil applies the IsNil predicate on the "mmi" field.
func MmiIsNil() predicate.FeltReport {
	return predicate.FeltReport(sql.FieldIsNull(FieldMmi))
}

// MmiNotNil applies the NotNil predicate on the "mmi" field.
func MmiNotNil() predicate.FeltReport {
	return predicate.FeltReport(sql.FieldNotNull(FieldMmi))
}

// AlertEQ applies the EQ predicate on the "alert" field.
func AlertEQ(v string) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldEQ(FieldAlert, v))
}

// AlertNEQ applies the NEQ predicate on the "alert" field.
func AlertNEQ(v string) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldNEQ(FieldAlert, v))
}

// AlertIn applies the In predicate on the "alert" field.
func AlertIn(vs ...string) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldIn(FieldAlert, vs...))
}

// AlertNotIn applies the NotIn predicate on the "alert" field.
func AlertNotIn(vs ...string) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldNotIn(FieldAlert, vs...))
}

// AlertGT applies the GT predicate on the "alert" field.
func AlertGT(v string) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldGT(FieldAlert, v))
}

// AlertGTE applies the GTE predicate on the "alert" field.
func AlertGTE(v string) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldGTE(FieldAlert, v))
}

// AlertLT applies the LT predicate on the "alert" field.
func AlertLT(v string) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldLT(FieldAlert, v))
}

// AlertLTE applies the LTE predicate on the "alert" field.
func AlertLTE(v string) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldLTE(FieldAlert, v))
}

// AlertContains applies the Contains predicate on the "alert" field.
func AlertContains(v string) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldContains(FieldAlert, v))
}

// AlertHasPrefix applies the HasPrefix predicate on the "alert" field.
func AlertHasPrefix(v string) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldHasPrefix(FieldAlert, v))
}

// AlertHasSuffix applies the HasSuffix predicate on the "alert" field.
func AlertHasSuffix(v string) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldHasSuffix(FieldAlert, v))
}

// AlertIsNil applies the IsNil predicate on the "alert" field.
func AlertIsNil() predicate.FeltReport {
	return predicate.FeltReport(sql.FieldIsNull(FieldAlert))
}

// AlertNotNil applies the NotNil predicate on the "alert" field.
func AlertNotNil() predicate.FeltReport {
	return predicate.FeltReport(sql.FieldNotNull(FieldAlert))
}

// AlertEqualFold applies the EqualFold predicate on the "alert" field.
func AlertEqualFold(v string) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldEqualFold(FieldAlert, v))
}

// AlertContainsFold applies the ContainsFold predicate on the "alert" field.
func AlertContainsFold(v string) predicate.FeltReport {
	return predicate.FeltReport(sql.FieldContainsFold(FieldAlert, v))
}

// HasEarthquake applies the HasEdge predicate on the "earthquake" edge.
func HasEarthquake() predicate.FeltReport {
	return predicate.FeltReport(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, EarthquakeTable, EarthquakeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEarthquakeWith applies the HasEdge predicate on the "earthquake" edge with a given conditions (other predicates).
func HasEarthquakeWith(preds ...predicate.Earthquake) predicate.FeltReport {
	return predicate.FeltReport(func(s *sql.Selector) {
		step := newEarthquakeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FeltReport) predicate.FeltReport {
	return predicate.FeltReport(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FeltReport) predicate.FeltReport {
	return predicate.FeltReport(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FeltReport) predicate.FeltReport {
	return predicate.FeltReport(sql.NotPredicates(p))
}
