// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// APIRequestLog is the predicate function for apirequestlog builders.
type APIRequestLog func(*sql.Selector)

// AssociatedEvent is the predicate function for associatedevent builders.
type AssociatedEvent func(*sql.Selector)

// Earthquake is the predicate function for earthquake builders.
type Earthquake func(*sql.Selector)

// Earthquake_db is the predicate function for earthquake_db builders.
type Earthquake_db func(*sql.Selector)

// EventType is the predicate function for eventtype builders.
type EventType func(*sql.Selector)

// FeatureType is the predicate function for featuretype builders.
type FeatureType func(*sql.Selector)

// FeltReport is the predicate function for feltreport builders.
type FeltReport func(*sql.Selector)

// Geometry is the predicate function for geometry builders.
type Geometry func(*sql.Selector)

// SchemaMigration is the predicate function for schemamigration builders.
type SchemaMigration func(*sql.Selector)
